# Generated by Django 3.0.3 on 2021-03-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activitie',
        ),
    ]
